# Uncomment the next line to define a global platform for your project
# source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'

# use_frameworks!
inhibit_all_warnings!
platform :ios, '10.0'

target 'UniversalAppSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UniversalAppSwift, see more popular framework from https://github.com/ipader/SwiftGuide/blob/master/2019/OpenSourceforSwift-Classification-MindNode.md
  # JSON
  pod 'SwiftyJSON', '4.3.0'
  
  # date
  pod 'SwiftDate', '6.1.0'

  # dataBase
  pod 'FMDB', '2.7.5'
  
  # layout
  pod 'SnapKit', '4.2.0'
  
  # animation
  pod 'Hero', '1.5.0'
  
  # Rx
  pod 'RxSwift', '5.1.1'
  pod 'RxCocoa', '5.1.1'
  
  # network
  pod 'Alamofire', '5.2.2'
  pod 'Moya', '14.0.0'
  pod 'Kingfisher', '5.14.1'
  
  # ui
  pod 'IGListKit', '4.0.0'
  pod 'RAMAnimatedTabBarController', '5.1.0'
  
  # tool
  pod 'CocoaLumberjack/Swift', '3.7.0'
  pod 'DeviceKit', '2.3.0'
  pod 'SwiftLint', :configurations => ['Debug']
  pod 'LookinServer', :configurations => ['Debug'] # Lookin see more in https://lookin.work/
  pod 'YYKit', '1.0.9'
  
end
